# monitoring/prometheus.yml
global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  - "alert_rules.yml"

alerting:
  alertmanagers:
    - static_configs:
        - targets:
            - alertmanager:9093

scrape_configs:
  - job_name: "sentiment-classifier"
    static_configs:
      - targets: ["sentiment-classifier-service:80"]
    metrics_path: "/metrics"
    scrape_interval: 10s

  - job_name: "node-exporter"
    static_configs:
      - targets: ["node-exporter:9100"]

---
# monitoring/alert_rules.yml
groups:
  - name: sentiment_classifier_alerts
    rules:
      - alert: HighErrorRate
        expr: rate(model_predictions_total{status=~"4..|5.."}[5m]) > 0.1
        for: 2m
        labels:
          severity: warning
        annotations:
          summary: "High error rate detected"
          description: "Error rate is {{ $value }} errors per second"

      - alert: HighLatency
        expr: histogram_quantile(0.95, rate(model_prediction_duration_seconds_bucket[5m])) > 2
        for: 2m
        labels:
          severity: warning
        annotations:
          summary: "High prediction latency"
          description: "95th percentile latency is {{ $value }} seconds"

      - alert: ServiceDown
        expr: up{job="sentiment-classifier"} == 0
        for: 1m
        labels:
          severity: critical
        annotations:
          summary: "Sentiment classifier service is down"
          description: "Service has been down for more than 1 minute"

      - alert: LowConfidencePredictions
        expr: rate(model_predictions_total[5m]) > 0 and rate(high_confidence_predictions_total[5m]) / rate(model_predictions_total[5m]) < 0.7
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: "High rate of low confidence predictions"
          description: "{{ $value }} of predictions have low confidence"

---
# monitoring/grafana-dashboard.json
{
  "dashboard":
    {
      "id": null,
      "title": "Sentiment Classifier Monitoring",
      "tags": ["ml", "sentiment"],
      "timezone": "browser",
      "panels":
        [
          {
            "id": 1,
            "title": "Prediction Rate",
            "type": "graph",
            "targets":
              [
                {
                  "expr": "rate(model_predictions_total[5m])",
                  "legendFormat": "Predictions/sec",
                },
              ],
            "yAxes": [{ "label": "Predictions per second", "min": 0 }],
            "xAxis": { "show": true },
            "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
          },
          {
            "id": 2,
            "title": "Prediction Latency",
            "type": "graph",
            "targets":
              [
                {
                  "expr": "histogram_quantile(0.50, rate(model_prediction_duration_seconds_bucket[5m]))",
                  "legendFormat": "50th percentile",
                },
                {
                  "expr": "histogram_quantile(0.95, rate(model_prediction_duration_seconds_bucket[5m]))",
                  "legendFormat": "95th percentile",
                },
                {
                  "expr": "histogram_quantile(0.99, rate(model_prediction_duration_seconds_bucket[5m]))",
                  "legendFormat": "99th percentile",
                },
              ],
            "yAxes": [{ "label": "Seconds", "min": 0 }],
            "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
          },
          {
            "id": 3,
            "title": "Model Accuracy Over Time",
            "type": "graph",
            "targets":
              [{ "expr": "model_accuracy", "legendFormat": "Accuracy" }],
            "yAxes": [{ "label": "Accuracy", "min": 0, "max": 1 }],
            "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
          },
          {
            "id": 4,
            "title": "Prediction Confidence Distribution",
            "type": "heatmap",
            "targets":
              [
                {
                  "expr": "rate(prediction_confidence_bucket[5m])",
                  "format": "heatmap",
                  "legendFormat": "{{le}}",
                },
              ],
            "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
          },
        ],
      "time": { "from": "now-1h", "to": "now" },
      "refresh": "30s",
    },
}
