apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: sentiment-classifier-binding
  namespace: staging
subjects:
  - kind: ServiceAccount
    name: sentiment-classifier
    namespace: staging
roleRef:
  kind: Role
  name: sentiment-classifier-role
  apiGroup: rbac.authorization.k8s.io
